### PR TITLE
use mixin to add functions so they work with _.chain.

### PR DESCRIPTION
**Pull request by davidworkman9**
Can now do stuff like this:

```
_.chain(someArr)
  .groupBy(function (x) { return x.y; })
  .mapObject(function (val) { return val * 5; })
  .value();
```

### CODE REVIEW

**Comment by wearhere** [comment]
Sorry for the late response @davidworkman9, I was out of town. Very cool, thanks!

**Comment by wearhere** [comment]
Updated the version to 0.2.3.

**Comment by davidworkman9** [comment]
Could you publish this to atmosphere?

**Comment by wearhere** [comment]
Done! Thanks for the reminder.

**Comment by davidworkman9** [comment]
Thanks!

**Comment by davidworkman9** [comment]
Thanks!

**Pull request merged**
